name: github-actions-applitools-eyes
description: 'Applitools Eyes GitHub Action'
author: 'Colby Fayock <hello@colbyfayock.com>'

runs:
  using: docker
  image: Dockerfile

inputs:
  APPLITOOLS_API_KEY:
    description: 'Unique API key from your Applitools account'
  APPLITOOLS_BATCH_ID:
    description: 'Unique ID for the test batch'
  appName:
    description: 'Name of the website or applitcation'
    default: 'Web App'
  baseUrl:
    description: 'The website URL to be craweled for visual regression testing'
  batchName:
    description: 'Name of the batch of tests (for display purpose only).'
    default: 'GitHub Action Workflow'
  concurrency:
    description: 'Number of Eyes tests that this Runner will run concurrently'
    default: 5
  cypressBrowser:
    description: 'Browser Cypress uses to run tests'
    default: 'chrome'
  errorOnFailure:
    description: 'Set an error status if any tests fail'
    default: true
  maxDepth:
    description: 'How many steps deep do you want to crawl the given website?'
    default: 1
  serverUrl:
    description: 'The URL of Eyes server'
  sitemapUrl:
    description: 'The URL of a website sitemap to be used for visual regression testing'